config/routes.rb
Rails.application.routes.draw do
  get "/welcome", to: "welcome#index"
  get "/dinos", to: "dinos#index"

 
  resources :dinos, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dinos_controller.rb
class DinosController < ApplicationController
    def index
      @dinos = ["t-rex", "pterodactyl", "triceratops", "brontosaurus"]
      
    end

    def show
      @dino =  "I'm the dino #{params[:id]}"
    end
  end 

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
      # says we want to send back plain text
    #   render plain: "Welcome!"
    # render json: { hello: "world" }
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_homepage.html.erb
 <footer>
    <ul>
      <li>About us</li>
      <li>Team</li>
      <li>Terms and conditions</li>
    </ul>
  </footer>

app/views/dinos/index.html.erb
<h1>Dinos rule ok</h1>
<h3>Ask me a question</h3>
<h3>Answer: I Dino</h3>
<h1>Dino by name</h1>
<ul>
  <% @dinos.each do |dino| %>
    <li><%= link_to dino, dino_path(dino) %></li>
  <% end %>
</ul>

app/views/dinos/show.html.erb
<%= link_to "Dinosaurs", dinos_path %>

<%= @dino %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dinos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome!</h1>